# arxivの学問領域の指定
subject: 'cat:cs.AI OR cat:cs.CV OR cat:cs.CL OR cat:cs.LG OR cat:stat.ML OR cat:eess.IV'

# 検索キーワード
keywords:
        medical image: 3
        laparoscopic: 2
        endoscopic: 2
        segmentation: 1
        semantic segmentation: 3
        instance segmentation: 3
        video object segmentation: 3
        object detection: 3
        video adaptation: 2
        vision and language: 2
        vision transformer: 1
        CLIP: 1
        3D CNN: 1
        class imbalance: 2
        long-tail: 2


# 通知の閾値
score_threshold: 0
